export const queryKeys = {
  leads: ['companies', 'leads'] as const,
  customers: ['companies', 'customers'] as const,
  company: (id: string) => ['companies', id] as const,
  companyContacts: (id: string) => ['companies', id, 'contacts'] as const,
  companyMeetings: (id: string) => ['companies', id, 'meetings'] as const,
  meetings: ['meetings'] as const,
  salesReps: ['salesreps'] as const,
  mailDrafts: ['maildrafts'] as const,
  mailDraftByMeeting: (meetingId: string) =>
    ['maildrafts', 'by-meeting', meetingId] as const,
  notifications: ['notifications'] as const,
  notificationsUnread: ['notifications', 'unread-count'] as const,
  dashboard: ['dashboard'] as const,
  goals: ['goals'] as const,
  me: ['auth', 'me'] as const,
  employees: ['employees'] as const,
  managedEmployees: ['employees', 'managed'] as const,
  tenders: ['tenders'] as const,
  tender: (id: string) => ['tenders', id] as const,
};
