using Oypa.Crm.Domain.Entities;
using Shouldly;

namespace Oypa.Crm.UnitTests.Features.Companies;

/// <summary>
/// CompanyNote entity domain davranışı birim testleri.
/// </summary>
public sealed class CompanyNoteTests
{
    // -----------------------------------------------------------------------
    // CompanyNote ctor — doğrulama
    // -----------------------------------------------------------------------

    [Fact]
    public void CompanyNote_EmptyContent_ThrowsArgumentException()
    {
        Should.Throw<ArgumentException>(() =>
            new CompanyNote(Guid.NewGuid(), string.Empty, null, "Yazar"));
    }

    [Fact]
    public void CompanyNote_WhitespaceContent_ThrowsArgumentException()
    {
        Should.Throw<ArgumentException>(() =>
            new CompanyNote(Guid.NewGuid(), "   ", null, "Yazar"));
    }

    [Fact]
    public void CompanyNote_ValidContent_PropertiesAreSetCorrectly()
    {
        var companyId = Guid.NewGuid();
        var authorId = Guid.NewGuid();

        var note = new CompanyNote(companyId, "Firma ile görüşme yapıldı.", authorId, "Umur KUTLU");

        note.CompanyId.ShouldBe(companyId);
        note.Content.ShouldBe("Firma ile görüşme yapıldı.");
        note.AuthorUserId.ShouldBe(authorId);
        note.AuthorName.ShouldBe("Umur KUTLU");
    }

    [Fact]
    public void CompanyNote_NullAuthorUserId_IsAllowed()
    {
        var note = new CompanyNote(Guid.NewGuid(), "Sistem notu.", null, "Sistem");

        note.AuthorUserId.ShouldBeNull();
        note.AuthorName.ShouldBe("Sistem");
    }

    [Fact]
    public void CompanyNote_AuthorNameIsSnapshot_StoredAsProvided()
    {
        const string authorName = "Avniye ÖNER";
        var note = new CompanyNote(Guid.NewGuid(), "Not içeriği", Guid.NewGuid(), authorName);

        note.AuthorName.ShouldBe(authorName);
    }

    [Fact]
    public void CompanyNote_Id_IsAutoGeneratedGuid()
    {
        var note = new CompanyNote(Guid.NewGuid(), "İçerik", null, "Yazar");

        note.Id.ShouldNotBe(Guid.Empty);
    }

    [Fact]
    public void CompanyNote_CreatedAtUtc_IsSetOnConstruction()
    {
        var before = DateTime.UtcNow.AddSeconds(-1);
        var note = new CompanyNote(Guid.NewGuid(), "İçerik", null, "Yazar");
        var after = DateTime.UtcNow.AddSeconds(1);

        note.CreatedAtUtc.ShouldBeInRange(before, after);
    }
}
