using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.AspNetCore.TestHost;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Oypa.Crm.Api.Middlewares;
using Oypa.Crm.Contracts.Auth;
using Oypa.Crm.Contracts.Common;
using Oypa.Crm.Infrastructure.Identity;
using Oypa.Crm.Infrastructure.Persistence;
using Shouldly;

namespace Oypa.Crm.IntegrationTests;

/// <summary>
/// CorrelationIdMiddleware davranışını uçtan uca doğrular:
/// <list type="bullet">
///   <item>Gelen <c>X-Correlation-Id</c> header'ı yanıtta aynen döner.</item>
///   <item>Header gönderilmezse yanıtta yine de <c>X-Correlation-Id</c> bulunur (otomatik üretilir).</item>
/// </list>
/// </summary>
public sealed class CorrelationIdMiddlewareTests : IClassFixture<CustomWebApplicationFactory>, IAsyncLifetime
{
    private readonly WebApplicationFactory<Program> _factory;
    private readonly HttpClient _client;

    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web)
    {
        Converters = { new JsonStringEnumConverter() }
    };

    public CorrelationIdMiddlewareTests(CustomWebApplicationFactory factory)
    {
        _factory = factory.WithWebHostBuilder(_ => { /* rate limiter override gerekmez; health endpoint açık */ });
        _client = _factory.CreateClient(new WebApplicationFactoryClientOptions
        {
            // Yanıt header'larını okuyabilmek için redirect'i takip etmiyoruz.
            AllowAutoRedirect = false
        });
    }

    public async Task InitializeAsync()
    {
        using var scope = _factory.Services.CreateScope();
        var sp = scope.ServiceProvider;

        var db = sp.GetRequiredService<AppDbContext>();
        await db.Database.EnsureCreatedAsync();

        var roleManager = sp.GetRequiredService<RoleManager<IdentityRole<Guid>>>();
        foreach (var role in new[] { "Admin", "Sales" })
        {
            if (!await roleManager.RoleExistsAsync(role))
                await roleManager.CreateAsync(new IdentityRole<Guid>(role));
        }

        var userManager = sp.GetRequiredService<UserManager<ApplicationUser>>();
        if (await userManager.FindByEmailAsync(CustomWebApplicationFactory.AdminEmail) is null)
        {
            var admin = new ApplicationUser
            {
                UserName = CustomWebApplicationFactory.AdminEmail,
                Email = CustomWebApplicationFactory.AdminEmail,
                FullName = "Test Yöneticisi",
                EmailConfirmed = true
            };
            var result = await userManager.CreateAsync(admin, CustomWebApplicationFactory.AdminPassword);
            if (result.Succeeded)
                await userManager.AddToRoleAsync(admin, "Admin");
        }
    }

    public Task DisposeAsync() => Task.CompletedTask;

    // -----------------------------------------------------------------------
    // X-Correlation-Id header testleri — /health endpointi yetki gerektirmez
    // -----------------------------------------------------------------------

    [Fact]
    public async Task Request_WithCorrelationIdHeader_ResponseContainsSameCorrelationId()
    {
        // Arrange
        var expectedCorrelationId = Guid.NewGuid().ToString("D");
        _client.DefaultRequestHeaders.Remove(CorrelationIdMiddleware.CorrelationIdHeader);
        _client.DefaultRequestHeaders.Add(CorrelationIdMiddleware.CorrelationIdHeader, expectedCorrelationId);

        // Act
        var response = await _client.GetAsync("/health");

        // Assert
        response.Headers.TryGetValues(CorrelationIdMiddleware.CorrelationIdHeader, out var values)
            .ShouldBeTrue("X-Correlation-Id header yanıtta bulunmalı");

        var returnedId = values!.FirstOrDefault();
        returnedId.ShouldBe(expectedCorrelationId, "Gönderilen CorrelationId aynen dönmeli");
    }

    [Fact]
    public async Task Request_WithoutCorrelationIdHeader_ResponseContainsAutoGeneratedCorrelationId()
    {
        // Arrange — header gönderilmez
        _client.DefaultRequestHeaders.Remove(CorrelationIdMiddleware.CorrelationIdHeader);

        // Act
        var response = await _client.GetAsync("/health");

        // Assert — middleware otomatik bir CorrelationId üretmeli
        response.Headers.TryGetValues(CorrelationIdMiddleware.CorrelationIdHeader, out var values)
            .ShouldBeTrue("Header gönderilmese bile X-Correlation-Id yanıtta olmalı");

        var returnedId = values!.FirstOrDefault();
        returnedId.ShouldNotBeNullOrWhiteSpace("Otomatik üretilen CorrelationId boş olmamalı");
    }

    [Fact]
    public async Task Request_WithDifferentCorrelationIds_EachResponseReflectsItsOwnId()
    {
        // Arrange — birbirinden farklı iki istek
        var id1 = "corr-" + Guid.NewGuid().ToString("N");
        var id2 = "corr-" + Guid.NewGuid().ToString("N");

        // Act — birinci istek
        using var request1 = new HttpRequestMessage(HttpMethod.Get, "/health");
        request1.Headers.Add(CorrelationIdMiddleware.CorrelationIdHeader, id1);
        var response1 = await _client.SendAsync(request1);

        // Act — ikinci istek
        using var request2 = new HttpRequestMessage(HttpMethod.Get, "/health");
        request2.Headers.Add(CorrelationIdMiddleware.CorrelationIdHeader, id2);
        var response2 = await _client.SendAsync(request2);

        // Assert
        response1.Headers.TryGetValues(CorrelationIdMiddleware.CorrelationIdHeader, out var vals1);
        response2.Headers.TryGetValues(CorrelationIdMiddleware.CorrelationIdHeader, out var vals2);

        var returnedId1 = vals1?.FirstOrDefault();
        var returnedId2 = vals2?.FirstOrDefault();

        returnedId1.ShouldBe(id1);
        returnedId2.ShouldBe(id2);
        returnedId1.ShouldNotBe(returnedId2, "İki farklı isteğin CorrelationId'si farklı olmalı");
    }

    [Fact]
    public async Task Request_OnAuthenticatedEndpoint_CorrelationIdStillPresent()
    {
        // Arrange — kimlik doğrulama gerektiren bir endpointe kimlik bilgisi olmadan istek
        // 401 dönse bile CorrelationId header'ı olmalı
        _client.DefaultRequestHeaders.Remove(CorrelationIdMiddleware.CorrelationIdHeader);
        _client.DefaultRequestHeaders.Authorization = null;

        var correlationId = "auth-test-" + Guid.NewGuid().ToString("N");

        using var request = new HttpRequestMessage(HttpMethod.Get, "/api/goals");
        request.Headers.Add(CorrelationIdMiddleware.CorrelationIdHeader, correlationId);

        // Act
        var response = await _client.SendAsync(request);

        // Assert — 401 bile olsa CorrelationId dönmeli
        response.StatusCode.ShouldBe(HttpStatusCode.Unauthorized);
        response.Headers.TryGetValues(CorrelationIdMiddleware.CorrelationIdHeader, out var values)
            .ShouldBeTrue("401 yanıtında da X-Correlation-Id header'ı olmalı");
        values!.First().ShouldBe(correlationId);
    }
}
